[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "fastsdk"
version = "0.0.2"
description = "Conveniently build an SDK for web apis. Handle file uploads, downloads and streaming. Interact with job services. Natively work with FastTaskAPI."
requires-python = ">=3.8"
authors = [
    { name = "SocAIty" }
]
license = { text = "GPLv3" }
readme = "README.md"
dependencies = [
    "tqdm",
    "httpx",
    "media-toolkit>=0.1.0",
    "singleton_decorator==1.0.0"
]

[project.optional-dependencies]
Azure = [
    "azure-storage-blob"
]
S3 =[
    "boto3"
]
Full = [
    "azure-storage-blob",
    "boto3"
]


[project.urls]
Repository = "https://github.com/SocAIty/fastSDK"
