[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "fastsdk"
version = "0.3.0"
description = "Turn any AI/web service (OpenAPI, Replicate, RunPod, APIPod) into a native-feeling Python client."
requires-python = ">=3.8"
authors = [
    { name = "SocAIty" }
]
license = {file = "LICENSE"}
readme = "README.md"
dependencies = [
    "httpx",
    "tqdm",
    "pydantic>=2.11.3",
    "meseex>=0.0.7",
    "media-toolkit>=00.02.22",
    "singleton_decorator==1.0.0",
    "jinja2>=3.1.6",
    "fastcloud>=0.0.14",
	"apipod-registry>=0.0.2",
    "socaity-schemas>=0.0.1",
]

[project.optional-dependencies]
dev = [
    "pytest"
]
replicate = [
    "replicate"
]

[project.scripts]
fastsdk = "fastsdk.cli:main"

[project.urls]
Repository = "https://github.com/SocAIty/fastsdk"
Homepage = "https://www.socaity.ai"

[tool.setuptools.package-data]
"fastsdk.sdk_factory" = ["*.j2"]
