[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "fastsdk"
version = "00.01.03"
description = "Conveniently build an SDK for web apis. Handle file uploads, downloads and streaming. Interact with job services. Natively work with FastTaskAPI."
requires-python = ">=3.8"
authors = [
    { name = "SocAIty" }
]
license = {file = "LICENSE"}
readme = "README.md"
dependencies = [
    "tqdm",
    "httpx",
    "media-toolkit>=00.02.02",
    "singleton_decorator==1.0.0",
    "pydantic>=2.10.4",
    "fastcloud>=0.0.5"
]

[project.optional-dependencies]
azure = [
    "azure-storage-blob"
]
S3 =[
    "boto3"
]
full = [
    "azure-storage-blob",
    "boto3"
]


[project.urls]
Repository = "https://github.com/SocAIty/fastSDK"
Homepage = "https://www.socaity.ai"